sprite $file_storage [64x64/16z] {
xPO9YYin34J7rbRrxt_VMPl88Z5jmMVFOzZdLRTThQ1_lxnX0NsxqjPZ1MJJTolq0aXOnPj-c1syGCCtxZZqdLkEVFDu2KXi_3E2xFgLdU-H-Eu4Uz-9HCSO
C_04tGmxNpxkc70ps_dprX-_Flwlpny0CFmM0Y39gYDwW5nzcsFFoskC302Z_FSHaZxfenqmbWCmHZjWhZvcyST7-Nk9hZvbVsER2EFUF-d2Yw-Z6n2r_tFz
Bs6W-Dvz_gmVS7HVNrOVMU0jKzqZFDBl520EufeVzWimm5Nb6pK7oLO1qnag3pH8TWfmkgaawYHpWkymkfaKdCm9ka4ObduUuVBbpdVOaozA7XOeV_j9djzS
lWdoh42Z5T_-kZ3oh417-gcBWcS58j9FNGJ4oGJDopSjUbu0veaFMEh5fvpuJjYVdZwE2WZO5U1OT0NF9i3uMCgGkbYEaCcEcT-FcOTf1dZwU-8wm8B-PAWk
cmouPxkXnVcE2zARUeLF0SxcZbwF4AaV1y0VDZfwbbH-lxk02HfUyhIzlVa2
}
