sprite $file_storage_2 [64x50/16z] {
jPG7ikiW34LLa009ultlzjkQdq8ATfnvP-2IukjwnW2K-_90Nn9y0tkLz8WwmN6eAOnWgGY7oGMUGLSuJ1TuWNk2exozM-9yk5z5LLJqZcXUN7SHHW3eNavI
ct6S_rb8EyCbmNdKQVcbZrN7FZ5pkewOaO_h8AUqeK_clWwFnMoBmDrZYG-FEqYNeSzEk3B627bwx2-NeMy8W6gAMm3c-c8dsjXVXgzRFxcuhACbDMaC0KaI
aOG7-c9SLIkxvC8jGI1rnIe1-buVQpSYknGaN-EhytTS4nclGS_r-V6fbPopvizewVIv3qcjnHvYHcY4vg1PPlZK3xJ0XA80yxxyr4SknXEiC4xwQ2tSZmZf
rncvhK4p6lgd_9y__r1VJG3p6i_C_TkYYRtrFoL1W5t_n3dyj_2V8H2x-czxnx_wNt_tdzxuRtF_DSXvY_Yq4ddztdZY3sVhUKAtdFxMV_tP_yGVINNNVmll
MwHxyqVix_tVKgeYQXM869dxouQR_nh-UrBJc_yfm0F-Yj7cFutlVxDgPlHo_ClB-v_gyjz_ReF_-CRVFlUVT_rlW_yzQv3rFLbpe-7uNGOVyfMItpFwBqif
y0EbS6Su3JS6QNo-hW2elKWwWPIc6BifIr--vTANmW3m3m
}
