sprite $kong [64x64/16z] {
xTLNWiCW30HG2Gbcxd_XD1Sv0NODsVtp-qiHs3Ckykyk5rNvHWAIp3C2T9dbn0EBp2d42w4oJa6i29lQFOo7a69yAWJm0O63HTeJY30qht4ICmbaWgI94JiT
3OzGSKQ2mzqHSbn0HoxxVO72uNcy7JGuEE_4Zbbqi7_54VsL9eiEtRNXrIBBn9qJkRcVhzuZiIZXD0FiYmLykL4KSpTlnekAVKIGpmM7bLGB-53lHIHNBVv4
ipiESjrYEd7amME14m_nZCf8YuxAI8i9JIhfL8kAjdAonO8sQzwBbOoslFpwMukE3baqM-ndbtsHrusQBVQtz_PxlD-YVvvpoflUczZxyoBAJRHjh3fep-lR
FAtzHDNUl2sRXHIlqrw0NcK7XiOZcRapN_QuGf6gHLfd_h1Ni2f3flPyV0q6hHULDsgB61SBgV6b_87BvGu
}
