sprite $oic [64x64/16z] {
xPM74kCm24IpeALD_lzxpsQSfalpJRdcTHMZ1qGGw_J7wT0XADt3ZV9Bz8Ywo7KtBjvaBceFs8ThhX05W0pFgf2zU8pRqFSva9moXktw2TlioSIliw_AELj4
fPbHFsK1u4aiZAng1V4QLdf4L2MUL3CZ8bSF-gxcBPkYUvKFT36NrtpkWDb1p9-apnioyha3hhH9l-ZRwaO5C5l7WhjiZlHJUqIuAPwtZCOJVehL2dtUClXK
PD3Ciwfu2zyjiqV2l3bWrsodDAuh5LDuZ36qRyiqz52m8jlpjf0zGh_S15CHqaGCOWHLqAvCzRvqOqj0flJ1rMXK8qoDjePUPjB6U8WJPStFBKSEKWdg63gC
76FOSf6KnwOBp7mBQvfOdzVXTar_zMm-x_8N_oYPU6JvBJG_2XD_ygxVVesD7vS585qjpKrZM0XDqqp3r5LFvbHuA9NXpTcMDt9pb74kIrPaM9wPPqrcMkPY
be9JqtkSRAnuRM1ltlrCrmolpF8gHXEBsP3ccpUhrAPIhftG9G0WwwLG0HIhfDy5fzKAqNwkd6RP_GV0i7UJIvdshEyzW5cfy-StREWt6fRL-BJbxr2Q_9IJ
qBxLQFglrg53Xmxz
}
