sprite $ollama_3 [64x64/16z] {
pLO7bkme32H72Tt_j1C4lJmt1db_hic3Iw4KiFhde9tJjmV6QYKZ8X7O6xEb4KQPJjz0kz0h7oI1xXenolj1eWv_vXUY5WiHkRVSaGXZ8wf7kcb4MLd-lgJb
luDeziJttNCXmglMbGWK6uw2UgYx6NkDYwNJo87jaTaD-mdAX5m1e4Iht52a208KLfxzb8mqq4hcn8Vz0-ge7D02rBsAUEB3bOybfmnjyhi-idyElOmvi9cJ
6FvblZQX4RKm__tzDmMhfVovy1NRjxjBemQEe04A_4mlvCKmurm_ZpI0vdfYPp7t4nGuS4Z1hPl2EETZcPdjPhSuTO0jj1qX3RmV1AIj195L4r5sImHslR5k
ag9MhBEzht4pD-9tOMIucmHcQylGk0Pw6MthpV2K2a39lfirtludL3xmG-lhtmCDWEyTsFoPZ-EOppFFVqe5vzzmuCSkw-1pE3rmxM7yW-eh_tIGrN_77uco
dbSVaRT8w0_wyyuSew8rzj-Zyw6tTbNQcLFzES0mWt6yzaTHm-oDsDZF2ljwk3-lnqytpjnyYlzt700t_9c6bxzxzdKx_cdULxad5VkFsPjbr-U93wOOiJD6
pdbriuPVByi4ejLViA4ImJHMxmV5NETNywP2HDxcrOY3Qj_RmfT6Z5R3Uvt2olUhMUD2ZC4PONvdMERf_AUVvylnCmIXBx9C_SHthFkmyjFzgzMAybFxdmMa
9FCJRVBKi9dCHIROltg79-h5nnVJRiqzFtdknM-44Qy_-GAKnsU-6uk0JP-1bFxqKvxRVHvd5VmBpptEVpTdhhLdxp-xBZTMFOApwj_19m
}
