sprite $ollama_2 [64x91/16z] {
xTP5SaGn38JX_L3V_xHXikglRciKJhHoMVeUcWxV9lv33t5rXMJIkK8owLmXcNIkKC_B9fNut7FofG7ULcIl3N_OyGVZInRQx0LPlGdmifw3_RyN-v9kt9_p
tllvuIi2poMMezzE-fhCSvMipsKMvbMyeGbuxIzm7LyKy8_tBwp9-M_E_U6Z_MZ3t_SqAbKwZOTH2KCL_DfJTUsDNXYxtdTd3nlqab3XtEL6Y_y_-BtraZ8J
g22fjl4uL5BYbGcA-CJapZzkmomUnxFPi0yTVy3rary0k5d_wbj3NpgEyYzbJ_mWSMoldvvdVyZyq3okDDVFUTx7lzSIFzPFpozJtxk0Mp_RVEuFu_iFtt_k
l_p_ZyRlrtlDl7ww__B_Dnn_jm
}
