sprite $ollama [256x256/16z] {
xDW7bgiw381XWvjijVtlzaqIxXaGWT1YNljElTNyYEB17GG3UKerGG78iIP-oODuKXc820kdcZ80v5HLH7z87SI3hkZF6LbV17EKB_LBXYgYJqnLzE5lq1zH
HmJJb_eJwXZzFUOVgkYKG6Qvl3_3R9sYScz_0GYeSzLVFlzGTQxUtXz8tw5uSNzQMEVUVl2exr6uj3-oleUtzYVK9HWlxEzHbzpLpyp2eCk0d-99yh2wZZpT
qHz4bqcwh3_f2hcjtrTTm_6Y_i2wfjxLdtHTkQY_wYf9z_HxqdMIMSxtSz8Fw8v-OT1FAFBvVa_w2TpHxta-1pNI1Vr93I4r-8R-sVWbTqbqghASxgzgf2wh
0UtwynFCDxxPEMSFJ8BaWT-f329lM8TKqq67-Y7dB6RKxaTNTAhua_s-s54_rwawbPhsGmO0Esdtq97T0vpijriiwjo3_UqYJUUV8Q8v0FUIT2gVxBUdERgN
gXEeRVjp51qJxruwr0ayrszVVkW6mQpV-lw7sLqvY7PpTge_wTJluHQTWBRpxsas_a7FEb5FzODESE_-23g1RVkZsCjoQJ3Od-alIvUPlT6aLJyzvTaxUMam
b90Uqaxy4Cc-P7wPGnYMeJRzrLx-YuFHZ7YqduAOFSQ8sNyNGi8VJVeJsPVoIDA9C_EtCtPZg6D4s6x-KSpBVtKmn-UFzZ8R0nqJ96pLpxFRVsKm7F3XIBzd
U_clNMSDx_zY7ajh1oQ1ZlRRGZSHT08QzgDzAqzuCG_0e_smTldRdGPYitvlLdPJdRbi3_SN7SFEB4DtzFCFRnz_XZbk_aKiBo51gLXJIfLgWHHamByyxbc6
N-9EH_g3h3t-xDQ40e-8r9GHaLX4z45Kc0WnnphjZwnZiBwCn6RzIIU2CwAESHetLI3HzuIW11x8xEqVrvVHtAm_s-UIOQwFmd-4Yg9hf0Bm7z6-PTQNWMRz
C7_yh-s0XgASWFGpXfZupUwF_SeoRVkBtVqQFSqFpESgketK3FDbkF-mJ6dMNzVUI_CVWIfp1jGzA3CdjAVPCiiqwpVhkXbpWZXLtQjc9dkQBRnX_l9Z_bvU
VpC3wNuCvlR-T9gBFDITZlJJfmC3lLx-T9hhtwS_w_NItwSVpM2Qz4St0t_N_dH7F_vz-kF__Py9qmkBRX3-JVs2a7pVlVGX0Sg_gJ_e6iRiEpVL-KnoHJ_k
TAI_wXZiwfUQl7khywdAddxx_clMJyVxCRWreVxp-ilsVehkaqZR--jD_Hz__WcYRmZqxhE-w3lYtQUVVsww_x7RzlmlmMqJYcnw_tTtzN_w_j6XpaXosqNH
6LpvpDAuttx_sZ1-2cwFm1ikW9vRzc___jcpMjYxVNfKYxejtpzXfoFzIUOVPZiVOixmW6gLpktL5RKG7dAAmNSBtx_Rz9lRCtSXbxLTVEtS0KMNY51DeSiw
aPhrcmkFKTGwdszl0KkGTKoeMN_FkWFrxXXFkWDnitv6NMSVVIrE03RiBxgP17TSqEqAKxF-h9jLTqRHpNB3_gHRYNTdUD6DP91tEj8lmBfHTkU0RiGD-nda
Mmy_gsFTHbAx_iowKN9dPTs8Swj-s9nFdJkhPzr8ieZmr_i3Y3OP_o3fLbBv-_CFg5j9TbV8eblXz_lhMZ3L1sHvJYEuQuGggYgCjPHQINHP_Le_ly1YEqBq
lNleUXzYzEuwVOp1zvtxqNK-0eek01byfTylv7FDthNaSsLz2xxPNzxNc_WckdxXBVnNUsUwP3U8G-6m6m7I-p_jh5bgXDl2e5k1cZw_a_Rz36OHEY9_ZZzD
HBK_A7i_4L-VulVjtO7Ev-KAzMeVulULEhLeVlnDcRkFe7w4_sxY1zMkhnObWq_mPvNTZRuCKATBZx_yb4SXhhdJ2q2Y-bDHq2X__v1h2_pxemBGva-e5zdG
Lo8cLERl8x5Pcq4tJbXq-Q-ReFvEibtx94r-tuYu6M4lzR-mrgR6d_aVzniW2oadMQ_z0mfndHt7GDJXlok_Lyo6_0Pkzq6Ne17-qcLYxAZ0XsWj_e3zr7T2
1z3YprkE_V9XMTRX3uqN8TbLlA5q-5DNWsPNyP9yaP2M-MCLrltxpe455VW3Tir_IWT0f7N-InZyTnu14j5g_8EACFVll0Q0TVxGZkd-_JwmhVDVl03TtcAz
5PVvqyQZlznSQPc_B_LpqW2Gb_c19tHiBLuKfoxpLvRDjxlWe_pNzlpCcu52d4DKspZm8wSBDLhbHvRDgQEVIIB_aV-Psg4ZprR02lpggnyRhbp-62OGQu4K
p2Us066L_ytmxqACmGsahk1a4eqBINg0hN-9t_nqxo9ytPB6nTpesHniv0Umf8CdxrrKvIzFgHZYmR09W2G98NpHi42_LTpVuOU7RYV-kr1eJ2M8qSrgz-8t
86qJR4OQLhRImXxswl-NO7imiT8RrMY4uwsamAys_dbypWq9bTwgX9vgP2bYwb_Wpy-sfu3qNXYVVJ3NqFmNbTS_eoODT582DrR8_n50RLBwkCSnRm5_KnX2
KEH7Bp-JyvkBkB2L59pv1M2C2waqwdIP1tvq8-jVxqCCdzl_oB_EGczZ3lP-KLomoozyA2ZXrVS_ylutl-RFdFvXdM-w7Clyu8CB0qDHfTN-NzZ9lz3d-4oP
17ec4yhzD5V6-FluJnNqBfxIdF3zimybujkKGPFO0FQb3SmF_9Iop7ynheUNpWTddfK4Vj3kSfDgPEyU8OUhhsN-D9Bw4k_xfYbp1L0ITa_i7n57ulzndLy-
_-cNP_dcjSHPorUulrTbPFM3jCpF_s8OSEeNs_rNJDC7sTNUlEFYHiB_PPsVyj36oqA_UylijOsA3vpNtIE6t7dNEZ-6mNe6gVxQkh5LmLpSE6A_beY_7f76
zc582lo-3YO0c92kV0LpinB9Qu7ywyyZhfoJDuF7_nMHl22H7w-vWXQkFIxLZVC_xPBEU_jiV6vsBWVsGiHrVj-cKh_JSuN8YeGjsn-X856xZF07PfB06whm
jpoL-W_zIgNl7BLWJzYlgigKDJbhyBVMvNzYU7SG6mSC6_Mn0rGxam6EIlnO9_AVBJvzlPcOqDwkvSV7d3v4Lb6f_xSquVpox7EHsjy-TkWmOO9AEksFTyvF
CEFdi674hnAU_qPyRuAhgC8F090ZSLt3mp-wWMFA97pHwNsXf5Y6xbqQuGTRY2kCBb-QbNSCMQfzabuNoYe5G8l_vXPcWb5-FbZs1q8rYdD8UjlyhPIYnW-G
h-u1TfQV_sXqqf3E-UK032RGvGVWJnZbhn9_i_A2Bhqi4mPKVag5F_T383g1NtvH8FqbXxFyKPK_PyWmtF_v31-areto71fV5edAsktlyUKQC8ZR1I_EfTSW
VnyUHpN--Xyr65y0y2vPZV26ijYgwDyQm7FxgIneXB-rG4pDZHUk2y8RIcBtR_QbyuUQAd_jllxmPlzh7nkjMg7vH_Q_eHi15FbhnFSne2H_Ax7KLhEL0s3f
VSbqrEI7YTeF3kMvqbXhH_w_dV0_Ppr-tsRA6WBRBiwxMVDKz4kFFqxPtpqk540t-NNMCV-LIOqVvcfVNEoyPhQmLPgoFX2eyBVMdEm0bNjaTRE5hwkTStys
fVXVyxCEq3XLCuDFPc7I_urQ_6dQ_mqJ5w0OTlq9pBi_TUAV5eIDt_YO3FpeIaw0gMww1When3zZctP0zkjITlKNaqjrgT1ErJ__wOgTfyMBNB3awAtvjtut
-gzBu1gj5TgvkW60rldJaWFIjw-l_Yk_zSKbW2qi5G5A6lm9rchVk4gpgcxD_GX8w-DVh8l-VmiqfsmN_VyL2OiWaT_XiWCouGGz9WNtdm9_KAX_403VqaDG
i3y7NEU_D0pWniCh-koDXlil8ItpWrBzXr1Gl-tbAz6M-Sl_yfjvnwlFbMJLowdPt_NvwvhnDURoKByUMyd1AjQ_05hcTze50AptCUKC0EMN023dAshueDbY
HPDVlm20-QcF5G2gw_cF_gm22DU7-UFc_4cTd_df_z_umr7yV07ypV_D_yslCFwVoL-9cg0Dvhy3-C-f_wRB_ytlUFXlRu4oFp_2WQFuope_beCA078J16Zm
drN_L9q_TwUVvnH0lXJgVoV1TR_pBHXHeVur_vC7bJ_5eD3-_FpdfEaV5VWJgm1oql2lKVyTypaJW6Lz5GdN-UCv1T3PJ_t8_HTmJFNlfi7VcYkdh01uyHl4
zVEl_jRRTChr5vSIVyGpjW0y0JOgyNDlGJoZ-HigyJSuuWOSNeKGrFWJdT018dTegV57fFr70ExHHbJZzz3P__U__Gnq-FE_5R1x0RlZ4_nNGT0Glojz0OZD
yOiclr00OiCBW2beyeC3OaAty-Md1A3Q_hbFuuQjejvCZPJvS-uh5cry-t5Mvm-TmtWV_jxzJDhyG07vAdXRVYGz_lXJwDinxT-GA0vgcB_p5szy_NlKvtVr
eFclwFF7VlhRkGEey-Ujxy3s_EFKvdTbu-RlY_zL_V5lv-Rlorzey-Ujcx-l09Ir-Ej_vB1pGUtT0LhzAHt-k7dpzoD0LEK_u19ataIQ_BuT4FzavdTD_YFk
0EV7T8hy-S3uVzRZZ_m4-8ZJNpt-TCG1g643m08_F_-X8rAWyitnBshmi-4l77Btjnf_Rm4_OG007NvixP0CECD-fnP_P4crfzpzhSAFhRbJxW2FIlmy_uNT
0NvAzhDE-sExJaa0vHrLXP-eAu2qhPXNNoN_a_F30UuVPVvZ4k1pjm3Ivq_7fF-34dyvnW0IsG98d_-RFnnX__dc_-O7XVp7a_Y_-QC2_ydZV_e0Fvwr_jDl
VsIhocFM_rc3dqxQ_vLFy1zZ0ENLBvFEzuyH3t701-eL10tmkqFZdrhyLsKbG0_m_sdoOzaw-OKdmUdpNtJ40KWX9Yr-RYiFPaFnIfLOjVWRTdTBxIX45lpN
uMz8nA_LFqCumlzF
}
