sprite $vertex [64x64/16z] {
xPI9gYin34E1CPBn_t_mIuS8JmCZykw-7PQknr5Kq_f1_74Coi1CUdrWzS7B_NobZnnmtt_v_OzOnAb5r8w_n00pKmLi-7fSUwU_VyL3Y_QNtlNe0sWEbXyE
pXVGdES2GRAspnyeFTcF-_i3pS50UxFlzvmJzTw-xR_Q9mPNp-hT6sR_y_ZsGQBy00L1wVlorUF_zc_p-_tl_7v_VV_jlwH_1UWzjWDmyPM_88rP3fnM-qLY
tMC3blo5-VryoV_7s_KlJ_tx_7fi7tlzgpyzokyUYawFw-yOYnybS7_vkDm3yfzp1mPs-U_tjoCr7LdMwbzx9su6ID82TV_gNVQg2pmFg1DzbLnqFq20H0aO
NGE4ZFusPTEiJvVG3itXliLgOpdS3X3Jijbz1FM-QskJ1CpLz-wGITbHOdj2vC1bzmE2-S1azotWb9D6Tnn3hmAJzI9om0FCh1U1dA1U1lE4zL8e_SMGzPNv
uny
}
