sprite $vertex_2 [64x64/16z] {
xPK7aiCm30CjaYx___3r2zBWJQ_6L0sr50P8wHv8Ys8SOtO-3BFpSPh6kVamJSCL-1FyNraHCsTMLgKvNubNVeu_j7_BSt_jcszNuTa_yzBrUVazZLTUf_Bg
y_JySXpphFvQKtwQdv3_RVcMgMiw7yQRtolYrPUal9bNNsOVyEhBxMD-Co_ju_puz-_AlFg2_h6_w_NV0OzzrJHL1_qRNdFRkCdBJ7SQgsochv-pwD9fWwyA
vgDgazTMMR3-TKtQM5ocRtF7Mn3lBe05yMQA5iJlZi12DdtUHEjnhysR4JjRINAAkL6Eb1jRWCSvHyWDBTZ7MP5_D3mE5k1n_XzvO2tw1
}
